<?php
/**
 * @var $block \HighQDev\Core\Block\ViewBlock
 */
?>

<?php
$comments = $block->getApprovedComments();
?>

<h2>Comments</h2>
<table class="custom-table">
    <thead>
    <tr>
        <th>SKU</th>
        <th>Comment</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($comments as $comment) {
        ?>
        <tr>
            <td> <?= $comment->getdata('sku') ?>
            </td>
            <td><?= $comment->getdata('comment_text') ?></td>
        </tr>
        <?php
    }
    ?>
    </tbody>
</table>
