<?php
declare(strict_types=1);

namespace HighQDev\Core\Model;
/**
 * Class Product
 * @package HighQDev\Core\Model
 */
class Product extends \Magento\Catalog\Model\Product
{
    /**
     * @return string
     */
    public function getName()
    {
        return parent::getName() . " discounted to 50%"; // TODO: Change the autogenerated stub
    }
}
