<?php
declare(strict_types=1);

namespace HighQDev\Core\Block;

use Magento\Checkout\Helper\Cart;
use Magento\Cms\Block\Block;
use Magento\Cms\Model\BlockFactory;
use Magento\Cms\Model\Template\FilterProvider;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\View\Element\Context;
use Magento\Store\Model\StoreManagerInterface;

/**
 * Class Offer
 * @package HighQDev\Core\Block
 */
class Offer extends Block
{
    /**
     * @var Cart
     */
    protected $helperCart;

    /**
     * @var ScopeConfigInterface
     */
    protected $scopeConfig;

    /**
     * Offer constructor.
     * @param Cart $cart
     * @param ScopeConfigInterface $scopeConfig
     * @param Context $context
     * @param FilterProvider $filterProvider
     * @param StoreManagerInterface $storeManager
     * @param BlockFactory $blockFactory
     * @param array $data
     */
    public function __construct(Cart $cart,
                                ScopeConfigInterface $scopeConfig,
                                Context $context,
                                FilterProvider $filterProvider,
                                StoreManagerInterface $storeManager,
                                BlockFactory $blockFactory,
                                array $data = [])
    {
        $this->helperCart = $cart;
        $this->scopeConfig = $scopeConfig;
        parent::__construct($context, $filterProvider, $storeManager, $blockFactory, $data);
    }

    /**
     * @return string
     */
    public function toHtml()
    {
        $offerEnable =  $this->scopeConfig->getValue('offers/general/enable', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
        if ($this->helperCart->getSummaryCount() > 2 && $offerEnable) {
            return parent::toHtml(); // TODO: Change the autogenerated stub
        } else {
            return "";
        }
    }
}
